# Site settings
name: Nikesh Balami
title: Nikesh Balami | Personal Website
description: A civic entrepreneur, open data advocate and tech researcher
url: https://nikeshbalami.github.io
baseurl: ''
email: nikeshbalami@gmail.com
cover: https://nikeshbalami.github.io/img/og.png
logo: https://nikeshbalami.github.io/img/emojis/technologist.png
resume: https://nikeshbalami.github.io/resume.pdf
social:
  - title: email
    url: mailto:nikeshbalami@gmail.com
  - title: twitter
    url: https://twitter.com/nikeshbalami
  - title: instagram
    url: https://instagram.com/nikeshbalami
  - title: github
    url: https://github.com/nikeshbalami
  - title: linkedin
    url: https://www.linkedin.com/in/nikeshbalami

# Build settings
markdown: kramdown

exclude:
  - 'Gemfile'
  - 'Gemfile.lock'
  - '*.gemspec'
  - 'README.md'
  - 'node_modules'
  - 'build'
  - 'gulpfile.js'
  - 'package.json'

keep_files:
  - 'CNAME'
  - '.git'
  - '.gitignore'

plugins_dir:
  - jekyll-minifier
  - jekyll-sitemap
